{{-- Seat Selector Modal / Popup for Sea Transport (Ferries) --}}
<div id="seatSelectorModal" class="modal" style="display: none; position: fixed; z-index: 1000; left: 0; top: 0; width: 100%; height: 100%; background-color: rgba(0,0,0,0.6); overflow: auto;">
    <div class="modal-content" style="background-color: #fff; margin: 5% auto; padding: 2rem; border-radius: 8px; max-width: 600px; width: 90%;">
        <div class="modal-header" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
            <h3 style="margin: 0;">Choose Your Seats</h3>
            <button type="button" class="close-modal" onclick="closeSeatSelector()" style="background: none; border: none; font-size: 24px; cursor: pointer; color: #666;">&times;</button>
        </div>

        <div class="seat-legend" style="display: flex; gap: 2rem; margin-bottom: 1.5rem; padding: 1rem; background: #f5f5f5; border-radius: 4px;">
            <div style="display: flex; align-items: center; gap: 0.5rem;">
                <div style="width: 30px; height: 30px; background: #fff; border: 2px solid #4CAF50; border-radius: 4px; cursor: pointer;"></div>
                <span>Available</span>
            </div>
            <div style="display: flex; align-items: center; gap: 0.5rem;">
                <div style="width: 30px; height: 30px; background: #f44336; border: 2px solid #f44336; border-radius: 4px; cursor: not-allowed;"></div>
                <span>Occupied</span>
            </div>
            <div style="display: flex; align-items: center; gap: 0.5rem;">
                <div style="width: 30px; height: 30px; background: #2196F3; border: 2px solid #2196F3; border-radius: 4px; cursor: pointer;"></div>
                <span>Selected</span>
            </div>
        </div>

        <div id="seatGrid" class="seat-grid" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.75rem; margin-bottom: 1.5rem; padding: 1rem; background: #f9f9f9; border-radius: 4px; max-height: 400px; overflow-y: auto;">
            {{-- Seat buttons will be generated by JavaScript --}}
        </div>

        <div class="seat-selection-info" style="padding: 1rem; background: #e8f5e9; border-radius: 4px; margin-bottom: 1.5rem;">
            <p style="margin: 0; font-size: 0.9rem;">
                <strong>Selected: </strong><span id="seatSelectionCount">0</span> 
                <span id="seatSelectionList" style="color: #1976D2;"></span>
            </p>
        </div>

        <div class="modal-actions" style="display: flex; gap: 1rem; justify-content: flex-end;">
            <button type="button" class="btn-secondary" onclick="closeSeatSelector()" style="padding: 0.75rem 1.5rem; background: #fff; border: 1px solid #ddd; border-radius: 4px; cursor: pointer; font-size: 1rem;">Cancel</button>
            <button type="button" class="btn-primary" onclick="confirmSeatSelection()" style="padding: 0.75rem 1.5rem; background: #4CAF50; color: #fff; border: none; border-radius: 4px; cursor: pointer; font-size: 1rem;">Confirm Selection</button>
        </div>
    </div>
</div>

<style>
.modal { animation: slideIn 0.3s ease-out; }
@keyframes slideIn {
    from { opacity: 0; }
    to { opacity: 1; }
}
.seat-grid {
    user-select: none;
}
.seat {
    width: 100%;
    aspect-ratio: 1;
    border: 2px solid #999;
    border-radius: 4px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.8rem;
    font-weight: 600;
    transition: all 0.2s ease;
    background: #fff;
}
.seat:hover:not(.occupied) {
    transform: scale(1.05);
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
}
.seat.occupied {
    background: #f44336;
    color: #fff;
    border-color: #f44336;
    cursor: not-allowed;
    opacity: 0.7;
}
.seat.selected {
    background: #2196F3;
    color: #fff;
    border-color: #1976D2;
}
.seat.available {
    background: #fff;
    color: #333;
    border-color: #4CAF50;
}
</style>

<script>
let selectedSeats = [];
let totalSeats = 0;
let occupiedSeats = [];

function initializeSeatSelector(totalSeatCount, occupiedSeatList = []) {
    totalSeats = totalSeatCount;
    occupiedSeats = Array.isArray(occupiedSeatList) ? occupiedSeatList : [];
    selectedSeats = [];
    
    const seatGrid = document.getElementById('seatGrid');
    seatGrid.innerHTML = '';
    
    // Generate seat grid (assume 4 seats per row)
    const cols = 4;
    const rows = Math.ceil(totalSeats / cols);
    
    let seatIndex = 0;
    for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
            if (seatIndex >= totalSeats) break;
            
            const seatNum = seatIndex + 1;
            const seatId = `seat-${seatNum}`;
            const isOccupied = occupiedSeats.includes(seatNum) || occupiedSeats.includes(seatId);
            
            const seatBtn = document.createElement('button');
            seatBtn.type = 'button';
            seatBtn.id = seatId;
            seatBtn.className = 'seat ' + (isOccupied ? 'occupied' : 'available');
            seatBtn.textContent = seatNum;
            seatBtn.disabled = isOccupied;
            
            if (!isOccupied) {
                seatBtn.onclick = (e) => {
                    e.preventDefault();
                    toggleSeat(seatNum, seatId);
                };
            }
            
            seatGrid.appendChild(seatBtn);
            seatIndex++;
        }
    }
}

function toggleSeat(seatNum, seatId) {
    const seatBtn = document.getElementById(seatId);
    if (!seatBtn) return;
    
    const index = selectedSeats.indexOf(seatNum);
    if (index > -1) {
        selectedSeats.splice(index, 1);
        seatBtn.classList.remove('selected');
        seatBtn.classList.add('available');
    } else {
        selectedSeats.push(seatNum);
        selectedSeats.sort((a, b) => a - b);
        seatBtn.classList.remove('available');
        seatBtn.classList.add('selected');
    }
    
    updateSeatSelectionDisplay();
}

function updateSeatSelectionDisplay() {
    const count = document.getElementById('seatSelectionCount');
    const list = document.getElementById('seatSelectionList');
    
    count.textContent = selectedSeats.length;
    if (selectedSeats.length > 0) {
        list.textContent = ` (${selectedSeats.join(', ')})`;
    } else {
        list.textContent = '';
    }
}

function openSeatSelector() {
    const modal = document.getElementById('seatSelectorModal');
    if (modal) modal.style.display = 'block';
}

function closeSeatSelector() {
    const modal = document.getElementById('seatSelectorModal');
    if (modal) modal.style.display = 'none';
}

function confirmSeatSelection() {
    if (selectedSeats.length === 0) {
        alert('Please select at least one seat');
        return;
    }
    
    // Store selected seats in a hidden input
    const seatInput = document.getElementById('selected_seats');
    if (seatInput) {
        seatInput.value = JSON.stringify(selectedSeats);
    }
    
    // Update display
    const seatDisplay = document.getElementById('selectedSeatsDisplay');
    if (seatDisplay) {
        seatDisplay.textContent = `Selected: ${selectedSeats.join(', ')}`;
    }
    
    closeSeatSelector();
}

// Close modal when clicking outside
window.onclick = function(event) {
    const modal = document.getElementById('seatSelectorModal');
    if (modal && event.target === modal) {
        modal.style.display = 'none';
    }
}
</script>
