{{-- Seat Selector Modal / Popup for Sea Transport (Ferries) --}}
<div id="seatSelectorModal" class="modal" style="display: none; position: fixed; z-index: 1000; left: 0; top: 0; width: 100%; height: 100%; background-color: rgba(0,0,0,0.6); overflow: auto;">
    <div class="modal-content" style="background-color: #fff; margin: 5% auto; padding: 2rem; border-radius: 8px; max-width: 600px; width: 90%;">
        <div class="modal-header" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
            <h3 id="seatModalTitle" style="margin: 0;">Choose Your Seats</h3>
            <button type="button" class="close-modal" onclick="closeSeatSelector()" style="background: none; border: none; font-size: 24px; cursor: pointer; color: #666;">&times;</button>
        </div>

        {{-- Step 1: Route / Leg Picker (shown when route_schedules exist) --}}
        <div id="routePickerStep" style="display: none;">
            <p style="margin: 0 0 1rem; color: #555; font-size: 0.9rem;">Select your route for this vessel:</p>
            <div id="routeLegList" style="display: flex; flex-direction: column; gap: 0.6rem; max-height: 360px; overflow-y: auto;"></div>
        </div>

        {{-- Step 2: Seat Grid --}}
        <div id="seatPickerStep">
            <div class="seat-legend" style="display: flex; gap: 2rem; margin-bottom: 1.5rem; padding: 1rem; background: #f5f5f5; border-radius: 4px;">
                <div style="display: flex; align-items: center; gap: 0.5rem;">
                    <div style="width: 30px; height: 30px; background: #fff; border: 2px solid #4CAF50; border-radius: 4px;"></div>
                    <span>Available</span>
                </div>
                <div style="display: flex; align-items: center; gap: 0.5rem;">
                    <div style="width: 30px; height: 30px; background: #f44336; border: 2px solid #f44336; border-radius: 4px;"></div>
                    <span>Occupied</span>
                </div>
                <div style="display: flex; align-items: center; gap: 0.5rem;">
                    <div style="width: 30px; height: 30px; background: #2196F3; border: 2px solid #2196F3; border-radius: 4px;"></div>
                    <span>Selected</span>
                </div>
            </div>

            <div id="seatGrid" class="seat-grid" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.75rem; margin-bottom: 1.5rem; padding: 1rem; background: #f9f9f9; border-radius: 4px; max-height: 400px; overflow-y: auto;">
                {{-- Seat buttons will be generated by JavaScript --}}
            </div>

            <div class="seat-selection-info" style="padding: 1rem; background: #e8f5e9; border-radius: 4px; margin-bottom: 1.5rem;">
                <p style="margin: 0; font-size: 0.9rem;">
                    <strong>Selected: </strong><span id="seatSelectionCount">0</span>
                    <span id="seatSelectionList" style="color: #1976D2;"></span>
                </p>
                <p id="selectedRouteLabel" style="margin: 0.4rem 0 0; font-size: 0.82rem; color: #555;"></p>
            </div>
        </div>

        <div class="modal-actions" style="display: flex; gap: 1rem; justify-content: flex-end; align-items: center;">
            <button type="button" id="routePickerBackBtn" onclick="showRoutePickerStep()" style="display: none; margin-right: auto; padding: 0.6rem 1rem; background: #fff; border: 1px solid #90a4ae; border-radius: 4px; cursor: pointer; font-size: 0.9rem; color: #37474f;">&#8592; Change Route</button>
            <button type="button" class="btn-secondary" onclick="closeSeatSelector()" style="padding: 0.75rem 1.5rem; background: #fff; border: 1px solid #ddd; border-radius: 4px; cursor: pointer; font-size: 1rem;">Cancel</button>
            <button type="button" id="seatConfirmBtn" class="btn-primary" onclick="confirmSeatSelection()" style="padding: 0.75rem 1.5rem; background: #4CAF50; color: #fff; border: none; border-radius: 4px; cursor: pointer; font-size: 1rem;">Confirm Selection</button>
        </div>
    </div>
</div>

<style>
.modal { animation: slideIn 0.3s ease-out; }
@keyframes slideIn {
    from { opacity: 0; }
    to { opacity: 1; }
}
.seat-grid {
    user-select: none;
}
.seat {
    width: 100%;
    aspect-ratio: 1;
    border: 2px solid #999;
    border-radius: 4px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.8rem;
    font-weight: 600;
    transition: all 0.2s ease;
    background: #fff;
}
.seat:hover:not(.occupied) {
    transform: scale(1.05);
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
}
.seat.occupied {
    background: #f44336;
    color: #fff;
    border-color: #f44336;
    cursor: not-allowed;
    opacity: 0.7;
}
.seat.selected {
    background: #2196F3;
    color: #fff;
    border-color: #1976D2;
}
.seat.available {
    background: #fff;
    color: #333;
    border-color: #4CAF50;
}
.route-leg-card {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    padding: 0.85rem 1rem;
    background: #fff;
    border: 2px solid #e0e0e0;
    border-radius: 8px;
    cursor: pointer;
    text-align: left;
    transition: border-color 0.15s, box-shadow 0.15s;
    width: 100%;
}
.route-leg-card:hover {
    border-color: #0f6179;
    box-shadow: 0 2px 8px rgba(15,97,121,0.12);
}
.leg-route-code {
    font-size: 0.72rem;
    font-weight: 700;
    color: #fff;
    background: #0f6179;
    border-radius: 3px;
    padding: 1px 6px;
    align-self: flex-start;
    letter-spacing: 0.03em;
}
.leg-od {
    font-size: 1rem;
    font-weight: 700;
    color: #1a2e3b;
}
.leg-arrow {
    color: #0f6179;
    margin: 0 4px;
}
.leg-time {
    font-size: 0.82rem;
    color: #546e7a;
}
.leg-days {
    font-size: 0.75rem;
    color: #78909c;
    margin-top: 1px;
}
</style>

<script>
let selectedSeats = [];
let totalSeats = 0;
let occupiedSeats = [];

function showRoutePickerStep() {
    window._seaTransportCurrentRouteCode = null;
    const routeStep = document.getElementById('routePickerStep');
    const seatStep  = document.getElementById('seatPickerStep');
    const backBtn   = document.getElementById('routePickerBackBtn');
    const confirmBtn = document.getElementById('seatConfirmBtn');
    const title     = document.getElementById('seatModalTitle');
    if (routeStep) routeStep.style.display = 'block';
    if (seatStep)  seatStep.style.display  = 'none';
    if (backBtn)   backBtn.style.display   = 'none';
    if (confirmBtn) confirmBtn.style.display = 'none';
    if (title)     title.textContent = 'Choose Your Route';
}

function showSeatPickerStep(routeCode, routeLabel) {
    window._seaTransportCurrentRouteCode = routeCode || null;
    const routeStep = document.getElementById('routePickerStep');
    const seatStep  = document.getElementById('seatPickerStep');
    const backBtn   = document.getElementById('routePickerBackBtn');
    const confirmBtn = document.getElementById('seatConfirmBtn');
    const title     = document.getElementById('seatModalTitle');
    const routeEl   = document.getElementById('selectedRouteLabel');
    if (routeStep) routeStep.style.display = 'none';
    if (seatStep)  seatStep.style.display  = 'block';
    if (backBtn)   backBtn.style.display   = routeCode ? 'inline-block' : 'none';
    if (confirmBtn) confirmBtn.style.display = 'inline-block';
    if (title)     title.textContent = 'Choose Your Seats';
    if (routeEl)   routeEl.textContent = routeLabel ? 'Route: ' + routeLabel : '';
    selectedSeats = [];
    updateSeatSelectionDisplay();
}

function initializeSeatSelector(totalSeatCount, occupiedSeatList = []) {
    totalSeats = totalSeatCount;
    occupiedSeats = Array.isArray(occupiedSeatList) ? occupiedSeatList : [];
    selectedSeats = [];
    
    const seatGrid = document.getElementById('seatGrid');
    seatGrid.innerHTML = '';
    
    // Generate seat grid (assume 4 seats per row)
    const cols = 4;
    const rows = Math.ceil(totalSeats / cols);
    
    let seatIndex = 0;
    for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
            if (seatIndex >= totalSeats) break;
            
            const seatNum = seatIndex + 1;
            const seatId = `seat-${seatNum}`;
            const isOccupied = occupiedSeats.includes(seatNum) || occupiedSeats.includes(seatId);
            
            const seatBtn = document.createElement('button');
            seatBtn.type = 'button';
            seatBtn.id = seatId;
            seatBtn.className = 'seat ' + (isOccupied ? 'occupied' : 'available');
            seatBtn.textContent = seatNum;
            seatBtn.disabled = isOccupied;
            
            if (!isOccupied) {
                seatBtn.onclick = (e) => {
                    e.preventDefault();
                    toggleSeat(seatNum, seatId);
                };
            }
            
            seatGrid.appendChild(seatBtn);
            seatIndex++;
        }
    }
}

function toggleSeat(seatNum, seatId) {
    const seatBtn = document.getElementById(seatId);
    if (!seatBtn) return;
    
    const index = selectedSeats.indexOf(seatNum);
    if (index > -1) {
        selectedSeats.splice(index, 1);
        seatBtn.classList.remove('selected');
        seatBtn.classList.add('available');
    } else {
        selectedSeats.push(seatNum);
        selectedSeats.sort((a, b) => a - b);
        seatBtn.classList.remove('available');
        seatBtn.classList.add('selected');
    }
    
    updateSeatSelectionDisplay();
}

function updateSeatSelectionDisplay() {
    const count = document.getElementById('seatSelectionCount');
    const list = document.getElementById('seatSelectionList');
    
    count.textContent = selectedSeats.length;
    if (selectedSeats.length > 0) {
        list.textContent = ` (${selectedSeats.join(', ')})`;
    } else {
        list.textContent = '';
    }
}

function openSeatSelector() {
    // Base implementation — overridden by catalog page for route-picker flow
    showSeatPickerStep(null, null);
    const modal = document.getElementById('seatSelectorModal');
    if (modal) modal.style.display = 'block';
}

function closeSeatSelector() {
    const modal = document.getElementById('seatSelectorModal');
    if (modal) modal.style.display = 'none';
}

function confirmSeatSelection() {
    if (selectedSeats.length === 0) {
        alert('Please select at least one seat');
        return;
    }

    closeSeatSelector();

    // Invoke booking callback if registered (sea transport catalog flow)
    if (typeof window._seaTransportSeatConfirmCallback === 'function') {
        window._seaTransportSeatConfirmCallback(selectedSeats.slice());
        return;
    }

    // Fallback: store in hidden input
    const seatInput = document.getElementById('selected_seats');
    if (seatInput) {
        seatInput.value = JSON.stringify(selectedSeats);
    }
    const seatDisplay = document.getElementById('selectedSeatsDisplay');
    if (seatDisplay) {
        seatDisplay.textContent = `Selected: ${selectedSeats.join(', ')}`;
    }
}

// Close modal when clicking outside
window.onclick = function(event) {
    const modal = document.getElementById('seatSelectorModal');
    if (modal && event.target === modal) {
        modal.style.display = 'none';
    }
}
</script>
