<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ strtolower((string) ($document_type ?? 'invoice')) === 'confirmation' ? 'Reservation Confirmation' : 'Invoice' }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #1f2a37; }
        .header { margin-bottom: 16px; }
        .title { font-size: 20px; font-weight: bold; margin: 0; }
        .muted { color: #4b5563; margin: 2px 0; }
        .grid { width: 100%; margin: 8px 0 16px; border-collapse: collapse; }
        .grid td { padding: 6px 8px; border: 1px solid #d1d5db; vertical-align: top; }
        .label { color: #374151; font-weight: 600; width: 30%; }
        .table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        .table th, .table td { border: 1px solid #d1d5db; padding: 8px; text-align: left; }
        .table th { background: #f3f4f6; }
        .right { text-align: right; }
        .total { font-weight: bold; background: #ecfeff; }
        .footer { margin-top: 20px; color: #4b5563; font-size: 11px; }
    </style>
</head>
<body>
    @php
        $docType = strtolower((string) ($document_type ?? 'invoice'));
        $isConfirmation = $docType === 'confirmation';
        $branding = $branding ?? workationBrandingProfile();
    @endphp

    @include('documents.partials.letterhead', ['branding' => $branding, 'isConfirmation' => $isConfirmation, 'generated_at' => $generated_at ?? ''])

    <table class="grid">
        <tr>
            <td class="label">Booking Reference</td>
            <td>{{ (string) ($booking_reference ?? '-') }}</td>
            <td class="label">Reservation ID</td>
            <td>#{{ (int) ($reservation_id ?? 0) }}</td>
        </tr>
        <tr>
            <td class="label">Customer</td>
            <td>{{ (string) ($customer_name ?? '-') }}</td>
            <td class="label">Customer Email</td>
            <td>{{ (string) ($customer_email ?? '-') }}</td>
        </tr>
        <tr>
            <td class="label">Service Dates</td>
            <td>{{ (string) ($start_at ?? '-') }} to {{ (string) ($end_at ?? '-') }}</td>
            <td class="label">Status</td>
            <td>{{ (string) ($status ?? '-') }} / {{ (string) ($payment_status ?? '-') }}</td>
        </tr>
        <tr>
            <td class="label">Payment Gateway</td>
            <td>{{ (string) ($payment_gateway ?? '-') }}</td>
            <td class="label">Payment Reference</td>
            <td>{{ (string) ($payment_reference ?? '') !== '' ? (string) ($payment_reference ?? '') : 'N/A' }}</td>
        </tr>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Description</th>
                <th class="right">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Base amount</td>
                <td class="right">{{ (string) ($currency ?? 'MVR') }} {{ number_format((float) ($subtotal_amount ?? 0), 2) }}</td>
            </tr>
            @if ((float) ($service_charge_total ?? 0) > 0)
                <tr>
                    <td>Service charge (included)</td>
                    <td class="right">{{ (string) ($currency ?? 'MVR') }} {{ number_format((float) ($service_charge_total ?? 0), 2) }}</td>
                </tr>
            @endif
            @if ((float) ($transfer_charge_total ?? 0) > 0)
                <tr>
                    <td>Transfer charge</td>
                    <td class="right">{{ (string) ($currency ?? 'MVR') }} {{ number_format((float) ($transfer_charge_total ?? 0), 2) }}</td>
                </tr>
            @endif
            <tr>
                <td>Taxes & fees (included)</td>
                <td class="right">{{ (string) ($currency ?? 'MVR') }} {{ number_format((float) ($total_tax_amount ?? 0), 2) }}</td>
            </tr>
            @foreach ((array) ($tax_lines ?? []) as $taxLine)
                <tr>
                    <td>{{ trim((string) ($taxLine['label'] ?? 'Tax')) }}</td>
                    <td class="right">{{ (string) ($currency ?? 'MVR') }} {{ number_format((float) ($taxLine['amount'] ?? 0), 2) }}</td>
                </tr>
            @endforeach
            <tr class="total">
                <td>Total</td>
                <td class="right">{{ (string) ($currency ?? 'MVR') }} {{ number_format((float) ($invoice_total_amount ?? 0), 2) }}</td>
            </tr>
        </tbody>
    </table>

    <p class="footer">This document is system-generated by Workation and can be used for booking and tax reference.</p>
</body>
</html>
