-- Idempotent migration to ensure ServiceCategory table exists and id is identity/sequence
DO $$
BEGIN
  -- Create table if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'ServiceCategory'
  ) THEN
    CREATE TABLE public."ServiceCategory" (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL,
      code text NOT NULL,
      active boolean NOT NULL,
      scope text NOT NULL,
      "createdAt" timestamptz NOT NULL DEFAULT now(),
      "updatedAt" timestamptz NOT NULL
    );
  ELSE
    -- If table exists but id column has no default/identity, attach an identity sequence
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema='public' AND table_name='ServiceCategory' AND column_name='id' AND (
        column_default IS NOT NULL OR is_identity = 'YES'
      )
    ) THEN
      -- create sequence (if not exists), set it to max(id)+1, and attach as default
      BEGIN
        EXECUTE 'CREATE SEQUENCE IF NOT EXISTS "ServiceCategory_id_seq" OWNED BY public."ServiceCategory".id';
      EXCEPTION WHEN others THEN
        -- ignore errors creating sequence
        RAISE NOTICE 'create sequence ignored';
      END;

      -- set sequence value to max(id)+1 (or 1)
      EXECUTE format('SELECT setval(%L, COALESCE((SELECT MAX(id) FROM public."ServiceCategory"),0) + 1, false)', '"ServiceCategory_id_seq"');

      -- set default to nextval of the sequence
      EXECUTE 'ALTER TABLE public."ServiceCategory" ALTER COLUMN id SET DEFAULT nextval(''"ServiceCategory_id_seq"'')';
    END IF;
  END IF;
END$$;
