-- Create ServiceCategory table for Postgres
CREATE TABLE IF NOT EXISTS public."ServiceCategory" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "code" text NOT NULL,
  "active" boolean NOT NULL,
  "scope" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL
);
