-- Ensure ServiceCategory.id is identity/sequence-backed (idempotent)
BEGIN;

DO $$
BEGIN
  -- If the id column already has an identity or a default, nothing to do
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ServiceCategory'
      AND column_name = 'id'
      AND (identity_generation IS NOT NULL OR column_default IS NOT NULL)
  ) THEN
    RAISE NOTICE 'ServiceCategory.id already has identity or default; skipping.';
  ELSE
    -- Try to convert the column to an IDENTITY column (Postgres 10+)
    BEGIN
      ALTER TABLE "ServiceCategory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
      RAISE NOTICE 'Converted ServiceCategory.id to IDENTITY.';
    EXCEPTION WHEN OTHERS THEN
      -- Fallback: create a sequence and attach it as default
      IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relkind = 'S' AND relname = 'servicecategory_id_seq') THEN
        CREATE SEQUENCE servicecategory_id_seq;
      END IF;

      PERFORM setval('servicecategory_id_seq', COALESCE((SELECT MAX("id") FROM "ServiceCategory"), 0) + 1);

      EXECUTE 'ALTER TABLE "ServiceCategory" ALTER COLUMN "id" SET DEFAULT nextval(''servicecategory_id_seq'')';
      EXECUTE 'ALTER SEQUENCE servicecategory_id_seq OWNED BY "ServiceCategory"."id"';
      RAISE NOTICE 'Attached servicecategory_id_seq as default for ServiceCategory.id.';
    END;
  END IF;
END
$$;

COMMIT;
