-- Create ServiceCategory table for Postgres
CREATE TABLE IF NOT EXISTS public."ServiceCategory" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "code" text NOT NULL UNIQUE,
  "active" boolean NOT NULL DEFAULT true,
  "scope" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);
