-- Create ServiceCategory table for Postgres
CREATE TABLE IF NOT EXISTS public."ServiceCategory" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "code" text NOT NULL UNIQUE,
  "active" boolean NOT NULL DEFAULT true,
  "scope" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

-- Idempotent fix for existing SQLite-style table without sequence/default
DO $$
BEGIN
  -- create sequence if missing
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'S' AND n.nspname = 'public' AND c.relname = 'ServiceCategory_id_seq'
  ) THEN
    EXECUTE 'CREATE SEQUENCE "ServiceCategory_id_seq"';
  END IF;

  -- attach sequence as default for ServiceCategory.id if column exists
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='ServiceCategory' AND column_name='id'
  ) THEN
    -- Only set default/attach sequence if column has no default AND is not an identity
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema='public' AND table_name='ServiceCategory' AND column_name='id'
        AND (column_default IS NOT NULL OR identity_generation IS NOT NULL)
    ) THEN
      -- protect against errors by executing in a begin-exception block
      BEGIN
        EXECUTE 'ALTER TABLE public."ServiceCategory" ALTER COLUMN "id" SET DEFAULT nextval(''"ServiceCategory_id_seq"'')::regclass';
        EXECUTE 'ALTER SEQUENCE "ServiceCategory_id_seq" OWNED BY public."ServiceCategory"."id"';
        EXECUTE format(
          'SELECT setval(%L, COALESCE((SELECT MAX("id")::bigint FROM public."ServiceCategory"), 0) + 1, false);',
          'ServiceCategory_id_seq'
        );
      EXCEPTION WHEN OTHERS THEN
        -- if something goes wrong (e.g., race with another process), skip and continue
        RAISE NOTICE 'Skipping attach sequence for ServiceCategory.id due to: %', SQLERRM;
      END;
    ELSE
      -- already has a default or is an identity column; nothing to do
      RAISE NOTICE 'ServiceCategory.id already has default or identity; skipping attach.';
    END IF;
  END IF;
END
$$;
